@startuml PlantFsm 

state Winter {
  Winter: entry / WinterIsComing
  state Freezing
  state Mild
  
  [*] --> Freezing
  Freezing -> Mild: TemperatureRises 
  Mild -> Freezing: TemperatureDrops
} 

state Spring {
  state Brisk
  state Temperate
  [*] --> Brisk
  Brisk -> Temperate: TemperatureRises
  Temperate -> Brisk: TemperatureDrops
}

state Summer {
  state Balmy
  state Scorching: entry / StartHeatWave 
  state Scorching: exit / EndHeatWave

  [*] --> Balmy
  Balmy -> Scorching: TemperatureRises
  Scorching -> Balmy: TemperatureDrops
}
state Autumn {
  state Pleasant
  state Crisp

  [*] --> Crisp
  Crisp -> Pleasant: TemperatureRises
  Pleasant -> Crisp: TemperatureDrops
}

[*] --> Winter
Winter --> Spring : TimeAdvances [EnoughTimePassed]
Spring --> Summer : TimeAdvances [EnoughTimePassed] / StartBlooming
Summer --> Autumn : TimeAdvances [EnoughTimePassed] / RipenFruit
Autumn --> Winter : TimeAdvances [EnoughTimePassed] / DropPetals 

@enduml
