@startuml PlantFsm 

state Winter {
  state Freezing
  state Mild
  
  [*] --> Freezing
  Freezing -> Mild: TemperatureRises 
  Mild -> Freezing: TemperatureDrops
} 

state Spring {
  state Chilly
  state Warmh
  [*] --> Chilly
  Chilly -> Warm: TemperatureRises
  Warm -> Chilly: TemperatureDrops
}

state Summer {
  state Warm
  state Hot

  [*] --> Warm
  Warm -> Hot: TemperatureRises
  Hot -> Warm: TemperatureDrops
}
state Autumn {
  state Warm
  state Chilly

  [*] --> Chilly
  Chilly -> Warm: TemperatureRises
  Warm -> Chilly: TemperatureDrops
}

[*] --> Winter
Winter --> Spring : TimeAdvances
Spring --> Summer : TimeAdvances / StartBlooming
Summer --> Autumn : TimeAdvances / RipenFruit
Autumn --> Winter : TimeAdvances / DropPetals 

@enduml
