@startuml DeferredEvents

[*] --> StateA

StateA: GoToA /defer
StateA: entry / enterA
StateA -> StateB: GoToB
StateA -> StateC: GoToC
StateA -> StateD: GoToD
StateA -> StateF: GoToF

StateB: entry / enterB
StateB -> StateA: GoToA

' Event is deferred again
StateC: GoToA /defer
StateC: entry / enterC
StateC -> StateB: GoToBFromC

' Event is deferred again after direct transition
StateD: GoToA /defer
StateD: entry / enterD
StateD -> StateB

' Substate inherits deferring from parent
state StateE {
  StateE: GoToA /defer
  state StateF : entry / enterF
  StateF -> StateB: GoToBFromF
}


@enduml
