@startuml EnterExitActions

[*] --> A

State A : entry / EnterA
State A : exit / ExitA

A -> A : GoToAFromA
A -> B : GoToB 
B -> A : GoToAFromB

' Composite state 
state C {
  C: entry / EnterC
  C: exit / ExitC

  '  parent enter/exit are overwritten by substates
  State C1 : entry / EnterC1
  State C1 : exit / ExitC1

  [*] --> C1
  C1 -> C2 : GoToC2
}
A -> C : GoToC
A -> C1 : GoToC1FromA
A -> C2 : GoToC2FromA
C -> A : GoToAFromC

@enduml
